# Generated by Django 2.2.6 on 2019-10-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20191024_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='e_to',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='n_to',
            new_name='row',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='x',
        ),
        migrations.RemoveField(
            model_name='room',
            name='y',
        ),
        migrations.AddField(
            model_name='room',
            name='wall_e',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='wall_n',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='wall_s',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='wall_w',
            field=models.BooleanField(default=True),
        ),
    ]
