# Generated by Django 2.2.6 on 2019-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20191024_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.TextField(default='Default Title'),
        ),
    ]
