# Generated by Django 2.2.6 on 2019-10-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20191024_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.TextField(),
        ),
    ]
