# Generated by Django 2.2.6 on 2019-10-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20191024_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='DEFAULT DESCRIPTION', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='DEFAULT TITLE', max_length=50),
        ),
    ]
